name: mage
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  build:
    name: mage build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      
      - name: Install dependencies
        run: go get .
      
      - name: cache golangci-lint
        id: cache-lint
        uses: actions/cache@v3
        with:
          path: bin/golangci-lint.exe
          key: ${{ hashFiles('magefile.go') }}
      
      - name: Run Mage
        uses: joshuacc/mage-action@master
        with:
          version: latest
          args: verify
      
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

