# This action triggers a new build of the ahkpm.dev documentation site so that
# it can rebuild with the latest version numbers, release links, etc.
name: redeploy docs
on: 
  # Every time a new release occurs
  release:
    types: [released]
  # Every day at midnight so that the ahkpm packages page is reasonably current
  schedule:
    - cron: "0 0 * * *" 

jobs:
  build:
    name: redeploy docs
    runs-on: ubuntu-latest

    steps:
      - run: curl -X POST -d {} $AHKPM_DEV_BUILD_HOOK
        env:
          AHKPM_DEV_BUILD_HOOK: ${{ secrets.AHKPM_DEV_BUILD_HOOK }}

