name: Go
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v -o bin/ahkpm.exe ./src
      # - name: Test with the Go CLI
      #   run: go test